services:
  api:
    build: .
    restart: on-failure
    volumes:
      - "./:/app"
    ports:
      - "3000:3000"
  db:
    image: mongo:latest
    attach: false
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - url_shortener_db_data:/data/db
  cache:
    image: redis:alpine
    restart: always
    # ports:
    #   - "6379:6379"
  # test-db:
  #   image: mongo:latest
  #   attach: false
  #   restart: always
volumes:
  url_shortener_db_data:
